# Generated by Django 2.1 on 2019-11-25 22:30

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wateroff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('date_of_off', models.DateTimeField()),
                ('date_of_on', models.DateTimeField()),
                ('reason', models.CharField(max_length=50)),
                ('adresses', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=blog.models.set_slug, max_length=150, unique=True),
        ),
    ]
