# Generated by Django 2.1 on 2019-11-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191126_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wateroff',
            name='city',
            field=models.CharField(max_length=50, verbose_name='Населенный пункт'),
        ),
        migrations.DeleteModel(
            name='Cities',
        ),
    ]
