# Generated by Django 2.1 on 2019-11-26 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_cities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wateroff',
            name='city',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='blog.Cities', verbose_name='Населенный пункт'),
        ),
    ]
