# Generated by Django 2.1 on 2019-11-26 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20191126_1202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wateroff',
            options={'ordering': ['id']},
        ),
    ]
