# Generated by Django 2.1 on 2019-11-26 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20191127_0927'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wateroff',
            options={'ordering': ['-id']},
        ),
    ]
