# Generated by Django 2.1 on 2019-12-03 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20191127_1148'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_pub'], 'verbose_name': 'Новости', 'verbose_name_plural': 'Новость'},
        ),
    ]
