# Generated by Django 2.1 on 2019-12-03 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20191204_1132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_pub'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
